title: Isha Jagdale
# logo: /assets/img/profile.png
description: >
  Software Developer specializing in Java, Flutter, Android Development,
  REST APIs, and modern application development.

show_downloads: false

theme: jekyll-theme-minimal

plugins:
  - jekyll-remote-theme

remote_theme: pages-themes/minimal@v0.2.0

github:
  is_project_page: false
